version: "3"
services:
  postgresql:
    image: "bitnami/postgresql:latest"
    container_name: cryptofu-db
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=tofu-dev
      - POSTGRESQL_PASSWORD=dev
      - POSTGRESQL_DATABASE=cryptofu
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

  bot:
    container_name: bot
    depends_on: 
      - postgresql
    build: .

volumes:
    postgres:
  